name: "systemMoniter-Server" #姓名
mode: "dev" #模式
port: 8085 #端口
log:
  level: "debug" #日志文件的位置
  filename: "systemMoniter-Server.log" #文件名字
  max_size: 200 #在进行切割之前，日志文件的最大大小（以MB为单位）
  max_age: 30 #保留旧文件的最大天数
  max_backups: 7 #保留旧文件的最大个数
mysql:
  host: "127.0.0.1" #数据库ip
  port: 3306 #数据库端口
  user: "root" #数据库用户名
  password: "123456" #数据库密码
  dbname: "systemMoniter" #数据库名字
  max_open_conns: 200 #设置与数据库建立连接的最大数目
  max_idle_conns: 50 #设置连接池中的最大闲置连接数
# redis:
#   host: "127.0.0.1" #地址
#   port: 6379 #端口
#   db: 0 # use default DB
#   password: "" #密码
#   pool_size: 100 #连接池大小
network: # 服务器端三网 ping 测试
  cu: "120.52.99.224"
  ct: "183.78.182.66"
  cm: "211.139.145.129"
  interval: 1 # ping 三网时间，0 为禁ping，分钟
sysadmin:
  user: "sys"
  password: "$2a$14$bYF334rdA/FP1R60MIBV4uD/3b8js6LVC6OxncCoMxLu8mwmhywOG" #123456

   